name: Deploy sklad.digital
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger remote deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: '[${{ secrets.LUCINKA_HOST }}]'
          username: ${{ secrets.LUCINKA_USER }}
          key: ${{ secrets.LUCINKA_DEPLOY_KEY }}
          script: |
